config/routes.rb
Rails.application.routes.draw do

  resources :videos
  resources :posts
  resources :incoming_contacts
  resources :driver_applications
  resources :app_settings
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  root to: "pages#show"
  resources :pages do
    collection {post :import} 
  end

  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'
end

app/views/layouts/pages/partials/show/_action_box.html.erb
<!-- beign #action-box -->
<div id="action-box" class="content has-bg" data-scrollview="true">
    <!-- begin content-bg -->
    <div class="content-bg">
      <img src="<%= asset_url "img/bg/bg-action.jpg" %>" alt="Action" />
    </div>
    <!-- end content-bg -->
    <!-- begin container -->
    <div class="container" data-animation="true" data-animation-type="fadeInRight">
      <!-- begin row -->
      <div class="row action-box">
        <!-- begin col-9 -->
        <div class="col-md-9 col-sm-9">
          <div class="icon-large text-theme">
            <i class="fa fa-truck"></i>
          </div>
          <h3><%= @page.action_box1 %></h3>
          <p> 
              
              <%= @page.action_box2 %>
          </p>
        </div>
        <!-- end col-9 -->
        <!-- begin col-3 -->
        <div class="col-md-3 col-sm-3">
        <%= link_to 'Apply Here', new_driver_application_path, class: "btn btn-outline btn-block", target: :blank %>

        </div>
        <!-- end col-3 -->
      </div>
      <!-- end row -->
    </div>
    <!-- end container -->
  </div>
  <!-- end #action-box -->

app/views/layouts/pages/partials/show/_client.html.erb
<!-- begin #client -->
<div id="client" class="content has-bg bg-green" data-scrollview="true">
    <!-- begin content-bg -->
    <div class="content-bg">
      <img src="../assets/img/bg/bg-client.jpg" alt="Client" />
    </div>
    <!-- end content-bg -->
    <!-- begin container -->
    <div class="container" data-animation="true" data-animation-type="fadeInUp">
      <h2 class="content-title">Our Client Testimonials</h2>
      <!-- begin carousel -->
      <div class="carousel testimonials slide" data-ride="carousel" id="testimonials">
        <!-- begin carousel-inner -->
        <div class="carousel-inner text-center">
          <!-- begin item -->
          <div class="item active">
            <blockquote>
              <i class="fa fa-quote-left"></i>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce viverra, nulla ut interdum fringilla,<br />
              urna massa cursus lectus, eget rutrum lectus neque non ex.
              <i class="fa fa-quote-right"></i>
            </blockquote>
            <div class="name"> — <span class="text-theme">Mark Doe</span>, Designer</div>
          </div>
          <!-- end item -->
          <!-- begin item -->
          <div class="item">
            <blockquote>
              <i class="fa fa-quote-left"></i>
              Donec cursus ligula at ante vulputate laoreet. Nulla egestas sit amet lorem non bibendum.<br />
              Nulla eget risus velit. Pellentesque tincidunt velit vitae tincidunt finibus.
              <i class="fa fa-quote-right"></i>
            </blockquote>
            <div class="name"> — <span class="text-theme">Joe Smith</span>, Developer</div>
          </div>
          <!-- end item -->
          <!-- begin item -->
          <div class="item">
            <blockquote>
              <i class="fa fa-quote-left"></i>
              Sed tincidunt quis est sed ultrices. Sed feugiat auctor ipsum, sit amet accumsan elit vestibulum<br />
              fringilla. In sollicitudin ac ligula eget vestibulum.
              <i class="fa fa-quote-right"></i>
            </blockquote>
            <div class="name"> — <span class="text-theme">Linda Adams</span>, Programmer</div>
          </div>
          <!-- end item -->
        </div>
        <!-- end carousel-inner -->
        <!-- begin carousel-indicators -->
        <ol class="carousel-indicators">
          <li data-target="#testimonials" data-slide-to="0" class="active"></li>
          <li data-target="#testimonials" data-slide-to="1" class=""></li>
          <li data-target="#testimonials" data-slide-to="2" class=""></li>

        </ol>
        <!-- end carousel-indicators -->
      </div>
      <!-- end carousel -->
    </div>
    <!-- end containter -->
  </div>
  <!-- end #client -->

app/views/layouts/pages/partials/show/_contact.html.erb
  <!-- begin #contact -->
<div id="contact" class="content bg-silver-lighter" data-scrollview="true">
    <!-- begin container -->
    <div class="container">
      <h2 class="content-title"><%= @page.string21 %></h2>
      <p class="content-desc">
          <%= @page.string22 %><br />
          <%= @page.string23 %>
      </p>
      <!-- begin row -->
      <div class="row">
        <!-- begin col-6 -->
        <div class="col-md-6" data-animation="true" data-animation-type="fadeInLeft">
          <h3><%= @page.string24 %></h3>
          <p>
              <%= @page.string25 %>
          </p>
          <p>
            <strong><%= @page.string26 %></strong><br />
            <%= @page.string27 %><br />
            <%= @page.string28 %><br />
            <%= @page.string29 %><br />
          </p>
          <p>
            <span class="phone"><%= @page.string30 %></span><br />
            <a href="mailto:<%= @page.string31 %>"><%= @page.string31 %></a>
          </p>
        </div>
        <!-- end col-6 -->
        <!-- begin col-6 -->
        <%= simple_form_for @incoming_contact do |ic| %>

        <div class="col-md-6 form-col" data-animation="true" data-animation-type="fadeInRight">
          <form class="form-horizontal">
            <div class="form-group">
              <label class="control-label col-md-3">Name <span class="text-theme">*</span></label>
              <div class="col-md-9">
                <%= ic.input :name, label: false %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3">Email <span class="text-theme">*</span></label>
              <div class="col-md-9">
                <%= ic.input :email, label: false %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3">Message <span class="text-theme">*</span></label>
              <div class="col-md-9">
                <%= ic.input :message, label: false %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3"></label>
              <div class="col-md-9 text-left">
              <%= ic.submit "Send Message", class: "btn btn-theme btn-block" %>
              </div>
            </div>
          </form>
        </div>
        <!-- end col-6 -->
        <% end %>
      </div>
      <!-- end row -->
    </div>
    <!-- end container -->
  </div>
  <!-- end #contact -->

app/views/layouts/pages/partials/show/_footer.html.erb
<!-- begin #footer -->
<div id="footer" class="footer">
    <div class="container">
      <div class="footer-brand">
          <%= link_to root_path do %>
          <span class=""><%= image_tag "traxx_logos/SVG/svg_logo_footer.svg" %></span>
          
          <% end %> 
      </div>
      <p>
        &copy; Copyright <%= Time.now.strftime("%Y")%> <%= @page.string46 %>  <br />
        <span><%= link_to "Terms of Use", terms_path, target: :_blank %></span> |     
        <span><%= link_to "Privacy Policy", privacy_path, target: :_blank %></span>
        

        <%= @page.string47 %> <a href="<%= @page.string40 %>"><%= @page.string48 %></a>
      </p>
      <p class="social-list">


        <%= link_to "http://#{@page.string41}", target: :_blank do %> 
        <i class="fab fa-facebook-square fa-fw"></i> 
        <% end %>
        <%= link_to "http://#{@page.string42}", target: :_blank do %> 
        <i class="fab fa-twitter-square fa-fw"></i>
        <% end %>
        <%= link_to "http://#{@page.string43}", target: :_blank do %> 
        <i class="fab fa-instagram fa-fw"></i>
        <% end %>
        <%= link_to "http://#{@page.string44}", target: :_blank do %> 
        <i class="fab fa-google-plus-square fa-fw"></i>
        <% end %>
        <%= link_to "http://#{@page.string45}", target: :_blank do %> 
        <i class="fab fa-linkedin fa-fw"></i>
        <% end %>
      </p>
    </div>
  </div>
  <!-- end #footer -->

app/views/layouts/pages/partials/show/_header.html.erb
<!-- begin #header -->
<div id="header" class="header navbar navbar-transparent navbar-fixed-top">
    <!-- class="header navbar navbar-inverse navbar-fixed-top" -->
    <!-- class="header navbar navbar-default navbar-fixed-top"> -->
    <!-- begin container -->
    <div class="container">
    <!-- begin navbar-header -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
      <span class="logo_span"><%= image_tag "traxx_logos/SVG/svg_logo.svg" %></span>
      
      <% end %>

    </div>
    <!-- end navbar-header -->

app/views/layouts/pages/partials/show/_home.html.erb
<!-- begin #home -->
<div id="home" class="content has-bg home">

    <!-- begin content-bg -->
    <div class="content-bg">
      <img src="<%= asset_url "custom/home_truck.jpg" %>" alt="Home" />
    </div>
    <!-- end content-bg -->
    <!-- begin container -->
    <div class="container home-content">
          <div class="container">
      <%= bootstrap_flash %>
    </div>
      <h1><%= @page.string1 %></h1>
      <h3><%= @page.string2 %></h3>
      <p>
          <%= @page.string3 %><br />
          <%= @page.string4 %> <a href="#"><%= @page.string5 %></a> <%= @page.string6 %>
      </p>
      <!-- <a href="#" class="btn btn-theme">Explore More</a> <a href="#" class="btn btn-outline">Purchase Now</a><br />
      <br />
      or <a href="#">subscribe</a> newsletter -->
    </div>
    <!-- end container -->
  </div>
  <!-- end #home -->

app/views/layouts/pages/partials/show/_navbar.html.erb
<!-- begin navbar-collapse -->
<div class="collapse navbar-collapse" id="header-navbar">
    <ul class="nav navbar-nav navbar-right">
      <!-- <li class="active dropdown">
        <a href="#home" data-click="scroll-to-target" data-toggle="dropdown">HOME <b class="caret"></b></a>
        <ul class="dropdown-menu dropdown-menu-left animated fadeInDown">
          <li><a href="#">Page with Transparent Header</a></li>
          <li><a href="#">Page with Inverse Header</a></li>
          <li><a href="#">Page with White Header</a></li>
          <li><a href="#">Extra Element</a></li>
        </ul>
      </li> -->
      <li><a href="#home" data-click="scroll-to-target">HOME</a></li>
      <li><a href="#about" data-click="scroll-to-target">ABOUT</a></li>
      <li><a href="#action-box" data-click="scroll-to-target">DRIVE</a></li>
      <!--<li><a href="#team" data-click="scroll-to-target">TEAM</a></li>-->
      <li><a href="#service" data-click="scroll-to-target">SERVICES</a></li>
      <!--<li><a href="#work" data-click="scroll-to-target">WORK</a></li>-->
      <!--<li><a href="#client" data-click="scroll-to-target">CLIENT</a></li>-->
      <!-- <li><a href="#pricing" data-click="scroll-to-target">PRICING</a></li> -->
      <li><a href="#contact" data-click="scroll-to-target">CONTACT</a></li>
      <% if current_user.try(:is_admin? ) %>
  

        <li class="active dropdown">
        <a href="#home" data-click="scroll-to-target" data-toggle="dropdown">user <b class="caret"></b></a>
        <ul class="dropdown-menu dropdown-menu-left animated fadeInDown">
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "App Settings", edit_app_setting_path(@app_setting) %></li>
          <li><%= link_to "Edit Page", edit_page_path(@page) %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path(@user) %></li>
          <li><a href="#">Extra Element</a></li>
        </ul>
      </li>
      <% end %>
    </ul>
  </div>
  <!-- end navbar-collapse -->
  </div>
  <!-- end container -->
  </div>
  <!-- end #header -->

app/views/layouts/pages/partials/show/_navbar2.html.erb
<!-- begin navbar-collapse -->
<div class="collapse navbar-collapse" id="header-navbar">
    <ul class="nav navbar-nav navbar-right">
      <!-- <li class="active dropdown">
        <a href="#home" data-click="scroll-to-target" data-toggle="dropdown">HOME <b class="caret"></b></a>
        <ul class="dropdown-menu dropdown-menu-left animated fadeInDown">
          <li><a href="#">Page with Transparent Header</a></li>
          <li><a href="#">Page with Inverse Header</a></li>
          <li><a href="#">Page with White Header</a></li>
          <li><a href="#">Extra Element</a></li>
        </ul>
      </li> -->
      <li><%= link_to "HOME", root_path %></li>
      <li><%= link_to "ARTICLES", posts_path %></li>
      <% if current_user.try(:is_admin? ) %>
  

        <li class="active dropdown">
        <a href="#home" data-click="scroll-to-target" data-toggle="dropdown">user <b class="caret"></b></a>
        <ul class="dropdown-menu dropdown-menu-left animated fadeInDown">
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "App Settings", edit_app_setting_path(@app_setting) %></li>
          <li><%= link_to "Edit Page", edit_page_path(@page) %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path(@user) %></li>
          <li><%= link_to "Posts", posts_path %></li>
        </ul>
      </li>
      <% end %>
    </ul>
  </div>
  <!-- end navbar-collapse -->
  </div>
  <!-- end container -->
  </div>
  <!-- end #header -->

app/views/layouts/pages/partials/show/_price.html.erb
<!-- begin #pricing -->
<div id="pricing" class="content" data-scrollview="true">
    <!-- begin container -->
    <div class="container">
      <h2 class="content-title">Our Price</h2>
      <p class="content-desc">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur eros dolor,<br />
        sed bibendum turpis luctus eget
      </p>
      <!-- begin pricing-table -->
      <ul class="pricing-table col-4">
        <li data-animation="true" data-animation-type="fadeInUp">
          <div class="pricing-container">
            <h3>Starter</h3>
            <div class="price">
              <div class="price-figure">
                <span class="price-number">FREE</span>
              </div>
            </div>
            <ul class="features">
              <li>1GB Storage</li>
              <li>2 Clients</li>
              <li>5 Active Projects</li>
              <li>5 Colors</li>
              <li>Free Goodies</li>
              <li>24/7 Email support</li>
            </ul>
            <div class="footer">
              <a href="#" class="btn btn-inverse btn-block">Buy Now</a>
            </div>
          </div>
        </li>
        <li data-animation="true" data-animation-type="fadeInUp">
          <div class="pricing-container">
            <h3>Basic</h3>
            <div class="price">
              <div class="price-figure">
                <span class="price-number">$9.99</span>
                <span class="price-tenure">per month</span>
              </div>
            </div>
            <ul class="features">
              <li>2GB Storage</li>
              <li>5 Clients</li>
              <li>10 Active Projects</li>
              <li>10 Colors</li>
              <li>Free Goodies</li>
              <li>24/7 Email support</li>
            </ul>
            <div class="footer">
              <a href="#" class="btn btn-inverse btn-block">Buy Now</a>
            </div>
          </div>
        </li>
        <li class="highlight" data-animation="true" data-animation-type="fadeInUp">
          <div class="pricing-container">
            <h3>Premium</h3>
            <div class="price">
              <div class="price-figure">
                <span class="price-number">$19.99</span>
                <span class="price-tenure">per month</span>
              </div>
            </div>
            <ul class="features">
              <li>5GB Storage</li>
              <li>10 Clients</li>
              <li>20 Active Projects</li>
              <li>20 Colors</li>
              <li>Free Goodies</li>
              <li>24/7 Email support</li>
            </ul>
            <div class="footer">
              <a href="#" class="btn btn-theme btn-block">Buy Now</a>
            </div>
          </div>
        </li>
        <li data-animation="true" data-animation-type="fadeInUp">
          <div class="pricing-container">
            <h3>Lifetime</h3>
            <div class="price">
              <div class="price-figure">
                <span class="price-number">$999</span>
              </div>
            </div>
            <ul class="features">
              <li>Unlimited Storage</li>
              <li>Unlimited Clients</li>
              <li>Unlimited Projects</li>
              <li>Unlimited Colors</li>
              <li>Free Goodies</li>
              <li>24/7 Email support</li>
            </ul>
            <div class="footer">
              <a href="#" class="btn btn-inverse btn-block">Buy Now</a>
            </div>
          </div>
        </li>
      </ul>
    </div>
    <!-- end container -->
  </div>
  <!-- end #pricing -->

app/views/layouts/pages/partials/show/_quote.html.erb
<!-- begin #quote -->
<div id="quote" class="content bg-black-darker has-bg" data-scrollview="true">
    <!-- begin content-bg -->
    <div class="content-bg">
      <img src="#" alt="Quote" />
    </div>
    <!-- end content-bg -->
    <!-- begin container -->
    <div class="container" data-animation="true" data-animation-type="fadeInLeft">
      <!-- begin row -->
      <div class="row">
        <!-- begin col-12 -->
        <div class="col-md-12 quote">
          <i class="fa fa-quote-left"></i> <%= @page.string61 %> <br />
          <%= @page.string62 %><span class="text-theme"><%= @page.string63 %></span>
          <i class="fa fa-quote-right"></i>
          <small><%= @page.string64 %></small>
        </div>
        <!-- end col-12 -->
      </div>
      <!-- end row -->
    </div>
    <!-- end container -->
  </div>
  <!-- end #quote -->

app/views/layouts/pages/partials/show/_service.html.erb
<!-- beign #service -->
<div id="service" class="content" data-scrollview="true">
    <!-- begin container -->
    <div class="container">
      <h2 class="content-title"><%= @page.string65 %></h2>
      <p class="content-desc">
        <%= @page.string66 %><br />
        <%= @page.string67 %>
      </p>
      <!-- begin row -->
      <div class="row">
        <!-- begin col-4 -->
        <div class="col-md-4 col-sm-4">
          <div class="service">
            <div class="icon bg-theme" data-animation="true" data-animation-type="bounceIn"><i class="fas fa-globe"></i></div>
            <div class="info">
              <h4 class="title"><%= @page.string68 %></h4>
              <p class="desc"><%= @page.string69 %></p>
            </div>
          </div>
        </div>
        <!-- end col-4 -->
        <!-- begin col-4 -->
        <div class="col-md-4 col-sm-4">
          <div class="service">
            <div class="icon bg-theme" data-animation="true" data-animation-type="bounceIn"><i class="fas fa-map-signs"></i></div>
            <div class="info">
              <h4 class="title"><%= @page.string70 %></h4>
              <p class="desc"><%= @page.string71 %></p>
            </div>
          </div>
        </div>
        <!-- end col-4 -->
        <!-- begin col-4 -->
        <div class="col-md-4 col-sm-4">
          <div class="service">
            <div class="icon bg-theme" data-animation="true" data-animation-type="bounceIn"><i class="fas fas fa-user"></i></div>
            <div class="info">
              <h4 class="title"><%= @page.string72 %></h4>
              <p class="desc"><%= @page.string73 %></p>
            </div>
          </div>
        </div>
        <!-- end col-4 -->
      </div>
      <!-- end row -->
      <!-- begin row -->
      <div class="row">
        <!-- begin col-4 -->
        <div class="col-md-4 col-sm-4">
          <div class="service">
            <div class="icon bg-theme" data-animation="true" data-animation-type="bounceIn"><i class="fas fa-lock"></i></div>
            <div class="info">
              <h4 class="title"><%= @page.string74 %></h4>
              <p class="desc"><%= @page.string75 %></p>
            </div>
          </div>
        </div>
        <!-- end col-4 -->
        <!-- begin col-4 -->
        <div class="col-md-4 col-sm-4">
          <div class="service">
            <div class="icon bg-theme" data-animation="true" data-animation-type="bounceIn"><i class="fas fa-hands-helping"></i></div>
            <div class="info">
              <h4 class="title"><%= @page.string76 %></h4>
              <p class="desc"><%= @page.string77 %></p>
            </div>
          </div>
        </div>
        <!-- end col-4 -->


        <!-- begin col-4 -->
        <div class="col-md-4 col-sm-4">
          <div class="service">
            <div class="icon bg-theme" data-animation="true" data-animation-type="bounceIn"><i class="fas fa-clock"></i></div>
            <div class="info">
              <h4 class="title"><%= @page.string78 %></h4>
              <p class="desc"><%= @page.string79 %></p>
            </div>
          </div>
        </div>
        <!-- end col-4 -->
      </div>
      <!-- end row -->
    </div>
    <!-- end container -->
  </div>
  <!-- end #service -->

app/views/layouts/pages/partials/show/_team.html.erb
<!-- begin #team -->
<div id="team" class="content" data-scrollview="true">
    <!-- begin container -->
    <div class="container">
      <h2 class="content-title"><%= @page.string49 %></h2>
      <p class="content-desc">
        <%= @page.string50 %><br /> 
        <%= @page.string51 %>
      </p>
      <!-- begin row -->
      <div class="row">
        <!-- begin col-4 -->
        <div class="col-md-4 col-sm-4">
          <!-- begin team -->
          <div class="team">
            <div class="image" data-animation="true" data-animation-type="flipInX">
              <img src="../assets/img/user/user-1.jpg" alt="<%= @page.string52 %>" />
            </div>
            <div class="info">
              <h3 class="name"><%= @page.string52 %></h3>
              <div class="title text-theme"><%= @page.string53 %></div>
              <p><%= @page.string54 %></p>
              <div class="social">
                  <a href="<%= @page.string45 %>"><i class="fab fa-linkedin fa-fw"></i></a> 
                  <a href="<%= @page.string41 %>"><i class="fab fa-facebook-square fa-fw"></i></a>
                  <a href="<%= @page.string43 %>"><i class="fab fa-twitter-square fa-fw"></i></a>
                </div>
            </div>
          </div>
          <!-- end team -->
        </div>
        <!-- end col-4 -->
        <!-- begin col-4 -->
        <div class="col-md-4 col-sm-4">
          <!-- begin team -->
          <div class="team">
            <div class="image" data-animation="true" data-animation-type="flipInX">
              <img src="../assets/img/user/user-2.jpg" alt="<%= @page.string52 %>" />
            </div>
            <div class="info">
              <h3 class="name"><%= @page.string55 %></h3>
              <div class="title text-theme"><%= @page.string56 %></div>
              <p><%= @page.string57 %></p>
              <div class="social">
                  <a href="<%= @page.string45 %>"><i class="fab fa-linkedin fa-fw"></i></a> 
                  <a href="<%= @page.string41 %>"><i class="fab fa-facebook-square fa-fw"></i></a>
                  <a href="<%= @page.string43 %>"><i class="fab fa-twitter-square fa-fw"></i></a>
                </div>
            </div>
          </div>
          <!-- end team -->
        </div>
        <!-- end col-4 -->
        <!-- begin col-4 -->
        <div class="col-md-4 col-sm-4">
          <!-- begin team -->
          <div class="team">
            <div class="image" data-animation="true" data-animation-type="flipInX">
              <img src="../assets/img/user/user-3.jpg" alt="<%= @page.string58 %>" />
            </div>
            <div class="info">
              <h3 class="name"><%= @page.string58 %></h3>
              <div class="title text-theme"><%= @page.string59 %></div>
              <p><%= @page.string60 %> </p>
              <div class="social">
                <a href="<%= @page.string45 %>"><i class="fab fa-linkedin fa-fw"></i></a> 
                <a href="<%= @page.string41 %>"><i class="fab fa-facebook-square fa-fw"></i></a>
                <a href="<%= @page.string43 %>"><i class="fab fa-twitter-square fa-fw"></i></a>
              </div>
            </div>
          </div>
          <!-- end team -->
        </div>
        <!-- end col-4 -->
      </div>
      <!-- end row -->
    </div>
    <!-- end container -->
  </div>
  <!-- end #team -->

app/views/layouts/pages/partials/show/_theme_picker.html.erb
<!-- begin theme-panel -->
<div class="theme-panel">
    <a href="javascript:;" data-click="theme-panel-expand" class="theme-collapse-btn"><i class="fa fa-cog"></i></a>
    <div class="theme-panel-content">
      <ul class="theme-list clearfix">
        <li><a href="javascript:;" class="bg-purple" data-theme="purple" data-theme-file="../assets/css/one-page-parallax/theme/purple.css" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Purple">&nbsp;</a></li>
        <li><a href="javascript:;" class="bg-blue" data-theme="blue" data-theme-file="../assets/css/one-page-parallax/theme/blue.css" data-theme-file="" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Blue">&nbsp;</a></li>
        <li class="active"><a href="javascript:;" class="bg-green" data-theme-file="../assets/css/one-page-parallax/theme/default.css" data-theme-file="" data-theme="default" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Default">&nbsp;</a></li>
        <li><a href="javascript:;" class="bg-orange" data-theme="orange" data-theme-file="../assets/css/one-page-parallax/theme/orange.css" data-theme-file="" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Orange">&nbsp;</a></li>
        <li><a href="javascript:;" class="bg-red" data-theme="red" data-theme-file="../assets/css/one-page-parallax/theme/red.css" data-theme-file="" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Red">&nbsp;</a></li>
      </ul>
    </div>
  </div>
  <!-- end theme-panel -->